// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shared/proto/sensor_data.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_shared_2fproto_2fsensor_5fdata_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_shared_2fproto_2fsensor_5fdata_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_shared_2fproto_2fsensor_5fdata_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_shared_2fproto_2fsensor_5fdata_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_shared_2fproto_2fsensor_5fdata_2eproto;
class AltimeterData;
struct AltimeterDataDefaultTypeInternal;
extern AltimeterDataDefaultTypeInternal _AltimeterData_default_instance_;
class ImuData;
struct ImuDataDefaultTypeInternal;
extern ImuDataDefaultTypeInternal _ImuData_default_instance_;
class SensorPacket;
struct SensorPacketDefaultTypeInternal;
extern SensorPacketDefaultTypeInternal _SensorPacket_default_instance_;
class Vector3D;
struct Vector3DDefaultTypeInternal;
extern Vector3DDefaultTypeInternal _Vector3D_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::AltimeterData* Arena::CreateMaybeMessage<::AltimeterData>(Arena*);
template<> ::ImuData* Arena::CreateMaybeMessage<::ImuData>(Arena*);
template<> ::SensorPacket* Arena::CreateMaybeMessage<::SensorPacket>(Arena*);
template<> ::Vector3D* Arena::CreateMaybeMessage<::Vector3D>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class Vector3D final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Vector3D) */ {
 public:
  inline Vector3D() : Vector3D(nullptr) {}
  ~Vector3D() override;
  explicit PROTOBUF_CONSTEXPR Vector3D(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Vector3D(const Vector3D& from);
  Vector3D(Vector3D&& from) noexcept
    : Vector3D() {
    *this = ::std::move(from);
  }

  inline Vector3D& operator=(const Vector3D& from) {
    CopyFrom(from);
    return *this;
  }
  inline Vector3D& operator=(Vector3D&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Vector3D& default_instance() {
    return *internal_default_instance();
  }
  static inline const Vector3D* internal_default_instance() {
    return reinterpret_cast<const Vector3D*>(
               &_Vector3D_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Vector3D& a, Vector3D& b) {
    a.Swap(&b);
  }
  inline void Swap(Vector3D* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Vector3D* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Vector3D* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Vector3D>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Vector3D& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Vector3D& from) {
    Vector3D::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Vector3D* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Vector3D";
  }
  protected:
  explicit Vector3D(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 3;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // @@protoc_insertion_point(class_scope:Vector3D)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    float x_;
    float y_;
    float z_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_shared_2fproto_2fsensor_5fdata_2eproto;
};
// -------------------------------------------------------------------

class ImuData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ImuData) */ {
 public:
  inline ImuData() : ImuData(nullptr) {}
  ~ImuData() override;
  explicit PROTOBUF_CONSTEXPR ImuData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ImuData(const ImuData& from);
  ImuData(ImuData&& from) noexcept
    : ImuData() {
    *this = ::std::move(from);
  }

  inline ImuData& operator=(const ImuData& from) {
    CopyFrom(from);
    return *this;
  }
  inline ImuData& operator=(ImuData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ImuData& default_instance() {
    return *internal_default_instance();
  }
  static inline const ImuData* internal_default_instance() {
    return reinterpret_cast<const ImuData*>(
               &_ImuData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ImuData& a, ImuData& b) {
    a.Swap(&b);
  }
  inline void Swap(ImuData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ImuData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ImuData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ImuData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ImuData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ImuData& from) {
    ImuData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ImuData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ImuData";
  }
  protected:
  explicit ImuData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAccelerationFieldNumber = 1,
    kAngularVelocityFieldNumber = 2,
  };
  // .Vector3D acceleration = 1;
  bool has_acceleration() const;
  private:
  bool _internal_has_acceleration() const;
  public:
  void clear_acceleration();
  const ::Vector3D& acceleration() const;
  PROTOBUF_NODISCARD ::Vector3D* release_acceleration();
  ::Vector3D* mutable_acceleration();
  void set_allocated_acceleration(::Vector3D* acceleration);
  private:
  const ::Vector3D& _internal_acceleration() const;
  ::Vector3D* _internal_mutable_acceleration();
  public:
  void unsafe_arena_set_allocated_acceleration(
      ::Vector3D* acceleration);
  ::Vector3D* unsafe_arena_release_acceleration();

  // .Vector3D angular_velocity = 2;
  bool has_angular_velocity() const;
  private:
  bool _internal_has_angular_velocity() const;
  public:
  void clear_angular_velocity();
  const ::Vector3D& angular_velocity() const;
  PROTOBUF_NODISCARD ::Vector3D* release_angular_velocity();
  ::Vector3D* mutable_angular_velocity();
  void set_allocated_angular_velocity(::Vector3D* angular_velocity);
  private:
  const ::Vector3D& _internal_angular_velocity() const;
  ::Vector3D* _internal_mutable_angular_velocity();
  public:
  void unsafe_arena_set_allocated_angular_velocity(
      ::Vector3D* angular_velocity);
  ::Vector3D* unsafe_arena_release_angular_velocity();

  // @@protoc_insertion_point(class_scope:ImuData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::Vector3D* acceleration_;
    ::Vector3D* angular_velocity_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_shared_2fproto_2fsensor_5fdata_2eproto;
};
// -------------------------------------------------------------------

class AltimeterData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:AltimeterData) */ {
 public:
  inline AltimeterData() : AltimeterData(nullptr) {}
  ~AltimeterData() override;
  explicit PROTOBUF_CONSTEXPR AltimeterData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AltimeterData(const AltimeterData& from);
  AltimeterData(AltimeterData&& from) noexcept
    : AltimeterData() {
    *this = ::std::move(from);
  }

  inline AltimeterData& operator=(const AltimeterData& from) {
    CopyFrom(from);
    return *this;
  }
  inline AltimeterData& operator=(AltimeterData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AltimeterData& default_instance() {
    return *internal_default_instance();
  }
  static inline const AltimeterData* internal_default_instance() {
    return reinterpret_cast<const AltimeterData*>(
               &_AltimeterData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(AltimeterData& a, AltimeterData& b) {
    a.Swap(&b);
  }
  inline void Swap(AltimeterData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AltimeterData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AltimeterData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AltimeterData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AltimeterData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AltimeterData& from) {
    AltimeterData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AltimeterData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "AltimeterData";
  }
  protected:
  explicit AltimeterData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPressureFieldNumber = 1,
    kAltitudeFieldNumber = 2,
    kTemperatureFieldNumber = 3,
  };
  // float pressure = 1;
  void clear_pressure();
  float pressure() const;
  void set_pressure(float value);
  private:
  float _internal_pressure() const;
  void _internal_set_pressure(float value);
  public:

  // float altitude = 2;
  void clear_altitude();
  float altitude() const;
  void set_altitude(float value);
  private:
  float _internal_altitude() const;
  void _internal_set_altitude(float value);
  public:

  // float temperature = 3;
  void clear_temperature();
  float temperature() const;
  void set_temperature(float value);
  private:
  float _internal_temperature() const;
  void _internal_set_temperature(float value);
  public:

  // @@protoc_insertion_point(class_scope:AltimeterData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    float pressure_;
    float altitude_;
    float temperature_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_shared_2fproto_2fsensor_5fdata_2eproto;
};
// -------------------------------------------------------------------

class SensorPacket final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SensorPacket) */ {
 public:
  inline SensorPacket() : SensorPacket(nullptr) {}
  ~SensorPacket() override;
  explicit PROTOBUF_CONSTEXPR SensorPacket(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SensorPacket(const SensorPacket& from);
  SensorPacket(SensorPacket&& from) noexcept
    : SensorPacket() {
    *this = ::std::move(from);
  }

  inline SensorPacket& operator=(const SensorPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline SensorPacket& operator=(SensorPacket&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SensorPacket& default_instance() {
    return *internal_default_instance();
  }
  static inline const SensorPacket* internal_default_instance() {
    return reinterpret_cast<const SensorPacket*>(
               &_SensorPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(SensorPacket& a, SensorPacket& b) {
    a.Swap(&b);
  }
  inline void Swap(SensorPacket* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SensorPacket* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SensorPacket* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SensorPacket>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SensorPacket& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SensorPacket& from) {
    SensorPacket::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SensorPacket* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SensorPacket";
  }
  protected:
  explicit SensorPacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kImuDataFieldNumber = 2,
    kAltimeterDataFieldNumber = 3,
    kTimestampFieldNumber = 1,
  };
  // .ImuData imu_data = 2;
  bool has_imu_data() const;
  private:
  bool _internal_has_imu_data() const;
  public:
  void clear_imu_data();
  const ::ImuData& imu_data() const;
  PROTOBUF_NODISCARD ::ImuData* release_imu_data();
  ::ImuData* mutable_imu_data();
  void set_allocated_imu_data(::ImuData* imu_data);
  private:
  const ::ImuData& _internal_imu_data() const;
  ::ImuData* _internal_mutable_imu_data();
  public:
  void unsafe_arena_set_allocated_imu_data(
      ::ImuData* imu_data);
  ::ImuData* unsafe_arena_release_imu_data();

  // .AltimeterData altimeter_data = 3;
  bool has_altimeter_data() const;
  private:
  bool _internal_has_altimeter_data() const;
  public:
  void clear_altimeter_data();
  const ::AltimeterData& altimeter_data() const;
  PROTOBUF_NODISCARD ::AltimeterData* release_altimeter_data();
  ::AltimeterData* mutable_altimeter_data();
  void set_allocated_altimeter_data(::AltimeterData* altimeter_data);
  private:
  const ::AltimeterData& _internal_altimeter_data() const;
  ::AltimeterData* _internal_mutable_altimeter_data();
  public:
  void unsafe_arena_set_allocated_altimeter_data(
      ::AltimeterData* altimeter_data);
  ::AltimeterData* unsafe_arena_release_altimeter_data();

  // uint32 timestamp = 1;
  void clear_timestamp();
  uint32_t timestamp() const;
  void set_timestamp(uint32_t value);
  private:
  uint32_t _internal_timestamp() const;
  void _internal_set_timestamp(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:SensorPacket)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::ImuData* imu_data_;
    ::AltimeterData* altimeter_data_;
    uint32_t timestamp_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_shared_2fproto_2fsensor_5fdata_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Vector3D

// float x = 1;
inline void Vector3D::clear_x() {
  _impl_.x_ = 0;
}
inline float Vector3D::_internal_x() const {
  return _impl_.x_;
}
inline float Vector3D::x() const {
  // @@protoc_insertion_point(field_get:Vector3D.x)
  return _internal_x();
}
inline void Vector3D::_internal_set_x(float value) {
  
  _impl_.x_ = value;
}
inline void Vector3D::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:Vector3D.x)
}

// float y = 2;
inline void Vector3D::clear_y() {
  _impl_.y_ = 0;
}
inline float Vector3D::_internal_y() const {
  return _impl_.y_;
}
inline float Vector3D::y() const {
  // @@protoc_insertion_point(field_get:Vector3D.y)
  return _internal_y();
}
inline void Vector3D::_internal_set_y(float value) {
  
  _impl_.y_ = value;
}
inline void Vector3D::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:Vector3D.y)
}

// float z = 3;
inline void Vector3D::clear_z() {
  _impl_.z_ = 0;
}
inline float Vector3D::_internal_z() const {
  return _impl_.z_;
}
inline float Vector3D::z() const {
  // @@protoc_insertion_point(field_get:Vector3D.z)
  return _internal_z();
}
inline void Vector3D::_internal_set_z(float value) {
  
  _impl_.z_ = value;
}
inline void Vector3D::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:Vector3D.z)
}

// -------------------------------------------------------------------

// ImuData

// .Vector3D acceleration = 1;
inline bool ImuData::_internal_has_acceleration() const {
  return this != internal_default_instance() && _impl_.acceleration_ != nullptr;
}
inline bool ImuData::has_acceleration() const {
  return _internal_has_acceleration();
}
inline void ImuData::clear_acceleration() {
  if (GetArenaForAllocation() == nullptr && _impl_.acceleration_ != nullptr) {
    delete _impl_.acceleration_;
  }
  _impl_.acceleration_ = nullptr;
}
inline const ::Vector3D& ImuData::_internal_acceleration() const {
  const ::Vector3D* p = _impl_.acceleration_;
  return p != nullptr ? *p : reinterpret_cast<const ::Vector3D&>(
      ::_Vector3D_default_instance_);
}
inline const ::Vector3D& ImuData::acceleration() const {
  // @@protoc_insertion_point(field_get:ImuData.acceleration)
  return _internal_acceleration();
}
inline void ImuData::unsafe_arena_set_allocated_acceleration(
    ::Vector3D* acceleration) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.acceleration_);
  }
  _impl_.acceleration_ = acceleration;
  if (acceleration) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ImuData.acceleration)
}
inline ::Vector3D* ImuData::release_acceleration() {
  
  ::Vector3D* temp = _impl_.acceleration_;
  _impl_.acceleration_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Vector3D* ImuData::unsafe_arena_release_acceleration() {
  // @@protoc_insertion_point(field_release:ImuData.acceleration)
  
  ::Vector3D* temp = _impl_.acceleration_;
  _impl_.acceleration_ = nullptr;
  return temp;
}
inline ::Vector3D* ImuData::_internal_mutable_acceleration() {
  
  if (_impl_.acceleration_ == nullptr) {
    auto* p = CreateMaybeMessage<::Vector3D>(GetArenaForAllocation());
    _impl_.acceleration_ = p;
  }
  return _impl_.acceleration_;
}
inline ::Vector3D* ImuData::mutable_acceleration() {
  ::Vector3D* _msg = _internal_mutable_acceleration();
  // @@protoc_insertion_point(field_mutable:ImuData.acceleration)
  return _msg;
}
inline void ImuData::set_allocated_acceleration(::Vector3D* acceleration) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.acceleration_;
  }
  if (acceleration) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(acceleration);
    if (message_arena != submessage_arena) {
      acceleration = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, acceleration, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.acceleration_ = acceleration;
  // @@protoc_insertion_point(field_set_allocated:ImuData.acceleration)
}

// .Vector3D angular_velocity = 2;
inline bool ImuData::_internal_has_angular_velocity() const {
  return this != internal_default_instance() && _impl_.angular_velocity_ != nullptr;
}
inline bool ImuData::has_angular_velocity() const {
  return _internal_has_angular_velocity();
}
inline void ImuData::clear_angular_velocity() {
  if (GetArenaForAllocation() == nullptr && _impl_.angular_velocity_ != nullptr) {
    delete _impl_.angular_velocity_;
  }
  _impl_.angular_velocity_ = nullptr;
}
inline const ::Vector3D& ImuData::_internal_angular_velocity() const {
  const ::Vector3D* p = _impl_.angular_velocity_;
  return p != nullptr ? *p : reinterpret_cast<const ::Vector3D&>(
      ::_Vector3D_default_instance_);
}
inline const ::Vector3D& ImuData::angular_velocity() const {
  // @@protoc_insertion_point(field_get:ImuData.angular_velocity)
  return _internal_angular_velocity();
}
inline void ImuData::unsafe_arena_set_allocated_angular_velocity(
    ::Vector3D* angular_velocity) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.angular_velocity_);
  }
  _impl_.angular_velocity_ = angular_velocity;
  if (angular_velocity) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ImuData.angular_velocity)
}
inline ::Vector3D* ImuData::release_angular_velocity() {
  
  ::Vector3D* temp = _impl_.angular_velocity_;
  _impl_.angular_velocity_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Vector3D* ImuData::unsafe_arena_release_angular_velocity() {
  // @@protoc_insertion_point(field_release:ImuData.angular_velocity)
  
  ::Vector3D* temp = _impl_.angular_velocity_;
  _impl_.angular_velocity_ = nullptr;
  return temp;
}
inline ::Vector3D* ImuData::_internal_mutable_angular_velocity() {
  
  if (_impl_.angular_velocity_ == nullptr) {
    auto* p = CreateMaybeMessage<::Vector3D>(GetArenaForAllocation());
    _impl_.angular_velocity_ = p;
  }
  return _impl_.angular_velocity_;
}
inline ::Vector3D* ImuData::mutable_angular_velocity() {
  ::Vector3D* _msg = _internal_mutable_angular_velocity();
  // @@protoc_insertion_point(field_mutable:ImuData.angular_velocity)
  return _msg;
}
inline void ImuData::set_allocated_angular_velocity(::Vector3D* angular_velocity) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.angular_velocity_;
  }
  if (angular_velocity) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(angular_velocity);
    if (message_arena != submessage_arena) {
      angular_velocity = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, angular_velocity, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.angular_velocity_ = angular_velocity;
  // @@protoc_insertion_point(field_set_allocated:ImuData.angular_velocity)
}

// -------------------------------------------------------------------

// AltimeterData

// float pressure = 1;
inline void AltimeterData::clear_pressure() {
  _impl_.pressure_ = 0;
}
inline float AltimeterData::_internal_pressure() const {
  return _impl_.pressure_;
}
inline float AltimeterData::pressure() const {
  // @@protoc_insertion_point(field_get:AltimeterData.pressure)
  return _internal_pressure();
}
inline void AltimeterData::_internal_set_pressure(float value) {
  
  _impl_.pressure_ = value;
}
inline void AltimeterData::set_pressure(float value) {
  _internal_set_pressure(value);
  // @@protoc_insertion_point(field_set:AltimeterData.pressure)
}

// float altitude = 2;
inline void AltimeterData::clear_altitude() {
  _impl_.altitude_ = 0;
}
inline float AltimeterData::_internal_altitude() const {
  return _impl_.altitude_;
}
inline float AltimeterData::altitude() const {
  // @@protoc_insertion_point(field_get:AltimeterData.altitude)
  return _internal_altitude();
}
inline void AltimeterData::_internal_set_altitude(float value) {
  
  _impl_.altitude_ = value;
}
inline void AltimeterData::set_altitude(float value) {
  _internal_set_altitude(value);
  // @@protoc_insertion_point(field_set:AltimeterData.altitude)
}

// float temperature = 3;
inline void AltimeterData::clear_temperature() {
  _impl_.temperature_ = 0;
}
inline float AltimeterData::_internal_temperature() const {
  return _impl_.temperature_;
}
inline float AltimeterData::temperature() const {
  // @@protoc_insertion_point(field_get:AltimeterData.temperature)
  return _internal_temperature();
}
inline void AltimeterData::_internal_set_temperature(float value) {
  
  _impl_.temperature_ = value;
}
inline void AltimeterData::set_temperature(float value) {
  _internal_set_temperature(value);
  // @@protoc_insertion_point(field_set:AltimeterData.temperature)
}

// -------------------------------------------------------------------

// SensorPacket

// uint32 timestamp = 1;
inline void SensorPacket::clear_timestamp() {
  _impl_.timestamp_ = 0u;
}
inline uint32_t SensorPacket::_internal_timestamp() const {
  return _impl_.timestamp_;
}
inline uint32_t SensorPacket::timestamp() const {
  // @@protoc_insertion_point(field_get:SensorPacket.timestamp)
  return _internal_timestamp();
}
inline void SensorPacket::_internal_set_timestamp(uint32_t value) {
  
  _impl_.timestamp_ = value;
}
inline void SensorPacket::set_timestamp(uint32_t value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:SensorPacket.timestamp)
}

// .ImuData imu_data = 2;
inline bool SensorPacket::_internal_has_imu_data() const {
  return this != internal_default_instance() && _impl_.imu_data_ != nullptr;
}
inline bool SensorPacket::has_imu_data() const {
  return _internal_has_imu_data();
}
inline void SensorPacket::clear_imu_data() {
  if (GetArenaForAllocation() == nullptr && _impl_.imu_data_ != nullptr) {
    delete _impl_.imu_data_;
  }
  _impl_.imu_data_ = nullptr;
}
inline const ::ImuData& SensorPacket::_internal_imu_data() const {
  const ::ImuData* p = _impl_.imu_data_;
  return p != nullptr ? *p : reinterpret_cast<const ::ImuData&>(
      ::_ImuData_default_instance_);
}
inline const ::ImuData& SensorPacket::imu_data() const {
  // @@protoc_insertion_point(field_get:SensorPacket.imu_data)
  return _internal_imu_data();
}
inline void SensorPacket::unsafe_arena_set_allocated_imu_data(
    ::ImuData* imu_data) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.imu_data_);
  }
  _impl_.imu_data_ = imu_data;
  if (imu_data) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:SensorPacket.imu_data)
}
inline ::ImuData* SensorPacket::release_imu_data() {
  
  ::ImuData* temp = _impl_.imu_data_;
  _impl_.imu_data_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::ImuData* SensorPacket::unsafe_arena_release_imu_data() {
  // @@protoc_insertion_point(field_release:SensorPacket.imu_data)
  
  ::ImuData* temp = _impl_.imu_data_;
  _impl_.imu_data_ = nullptr;
  return temp;
}
inline ::ImuData* SensorPacket::_internal_mutable_imu_data() {
  
  if (_impl_.imu_data_ == nullptr) {
    auto* p = CreateMaybeMessage<::ImuData>(GetArenaForAllocation());
    _impl_.imu_data_ = p;
  }
  return _impl_.imu_data_;
}
inline ::ImuData* SensorPacket::mutable_imu_data() {
  ::ImuData* _msg = _internal_mutable_imu_data();
  // @@protoc_insertion_point(field_mutable:SensorPacket.imu_data)
  return _msg;
}
inline void SensorPacket::set_allocated_imu_data(::ImuData* imu_data) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.imu_data_;
  }
  if (imu_data) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(imu_data);
    if (message_arena != submessage_arena) {
      imu_data = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, imu_data, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.imu_data_ = imu_data;
  // @@protoc_insertion_point(field_set_allocated:SensorPacket.imu_data)
}

// .AltimeterData altimeter_data = 3;
inline bool SensorPacket::_internal_has_altimeter_data() const {
  return this != internal_default_instance() && _impl_.altimeter_data_ != nullptr;
}
inline bool SensorPacket::has_altimeter_data() const {
  return _internal_has_altimeter_data();
}
inline void SensorPacket::clear_altimeter_data() {
  if (GetArenaForAllocation() == nullptr && _impl_.altimeter_data_ != nullptr) {
    delete _impl_.altimeter_data_;
  }
  _impl_.altimeter_data_ = nullptr;
}
inline const ::AltimeterData& SensorPacket::_internal_altimeter_data() const {
  const ::AltimeterData* p = _impl_.altimeter_data_;
  return p != nullptr ? *p : reinterpret_cast<const ::AltimeterData&>(
      ::_AltimeterData_default_instance_);
}
inline const ::AltimeterData& SensorPacket::altimeter_data() const {
  // @@protoc_insertion_point(field_get:SensorPacket.altimeter_data)
  return _internal_altimeter_data();
}
inline void SensorPacket::unsafe_arena_set_allocated_altimeter_data(
    ::AltimeterData* altimeter_data) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.altimeter_data_);
  }
  _impl_.altimeter_data_ = altimeter_data;
  if (altimeter_data) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:SensorPacket.altimeter_data)
}
inline ::AltimeterData* SensorPacket::release_altimeter_data() {
  
  ::AltimeterData* temp = _impl_.altimeter_data_;
  _impl_.altimeter_data_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::AltimeterData* SensorPacket::unsafe_arena_release_altimeter_data() {
  // @@protoc_insertion_point(field_release:SensorPacket.altimeter_data)
  
  ::AltimeterData* temp = _impl_.altimeter_data_;
  _impl_.altimeter_data_ = nullptr;
  return temp;
}
inline ::AltimeterData* SensorPacket::_internal_mutable_altimeter_data() {
  
  if (_impl_.altimeter_data_ == nullptr) {
    auto* p = CreateMaybeMessage<::AltimeterData>(GetArenaForAllocation());
    _impl_.altimeter_data_ = p;
  }
  return _impl_.altimeter_data_;
}
inline ::AltimeterData* SensorPacket::mutable_altimeter_data() {
  ::AltimeterData* _msg = _internal_mutable_altimeter_data();
  // @@protoc_insertion_point(field_mutable:SensorPacket.altimeter_data)
  return _msg;
}
inline void SensorPacket::set_allocated_altimeter_data(::AltimeterData* altimeter_data) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.altimeter_data_;
  }
  if (altimeter_data) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(altimeter_data);
    if (message_arena != submessage_arena) {
      altimeter_data = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, altimeter_data, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.altimeter_data_ = altimeter_data;
  // @@protoc_insertion_point(field_set_allocated:SensorPacket.altimeter_data)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_shared_2fproto_2fsensor_5fdata_2eproto
