// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sensor_data.proto
// Protobuf C++ Version: 6.32.1

#ifndef sensor_5fdata_2eproto_2epb_2eh
#define sensor_5fdata_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "google/protobuf/timestamp.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_sensor_5fdata_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_sensor_5fdata_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_sensor_5fdata_2eproto;
}  // extern "C"
class AltimeterData;
struct AltimeterDataDefaultTypeInternal;
extern AltimeterDataDefaultTypeInternal _AltimeterData_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull AltimeterData_class_data_;
class ImuData;
struct ImuDataDefaultTypeInternal;
extern ImuDataDefaultTypeInternal _ImuData_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ImuData_class_data_;
class SensorPacket;
struct SensorPacketDefaultTypeInternal;
extern SensorPacketDefaultTypeInternal _SensorPacket_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull SensorPacket_class_data_;
class Vector3D;
struct Vector3DDefaultTypeInternal;
extern Vector3DDefaultTypeInternal _Vector3D_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Vector3D_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class Vector3D final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Vector3D) */ {
 public:
  inline Vector3D() : Vector3D(nullptr) {}
  ~Vector3D() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Vector3D* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Vector3D));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Vector3D(::google::protobuf::internal::ConstantInitialized);

  inline Vector3D(const Vector3D& from) : Vector3D(nullptr, from) {}
  inline Vector3D(Vector3D&& from) noexcept
      : Vector3D(nullptr, ::std::move(from)) {}
  inline Vector3D& operator=(const Vector3D& from) {
    CopyFrom(from);
    return *this;
  }
  inline Vector3D& operator=(Vector3D&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Vector3D& default_instance() {
    return *reinterpret_cast<const Vector3D*>(
        &_Vector3D_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Vector3D& a, Vector3D& b) { a.Swap(&b); }
  inline void Swap(Vector3D* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Vector3D* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Vector3D* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Vector3D>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Vector3D& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Vector3D& from) { Vector3D::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Vector3D* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Vector3D"; }

 protected:
  explicit Vector3D(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Vector3D(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Vector3D& from);
  Vector3D(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Vector3D&& from) noexcept
      : Vector3D(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // float x = 1;
  void clear_x() ;
  float x() const;
  void set_x(float value);

  private:
  float _internal_x() const;
  void _internal_set_x(float value);

  public:
  // float y = 2;
  void clear_y() ;
  float y() const;
  void set_y(float value);

  private:
  float _internal_y() const;
  void _internal_set_y(float value);

  public:
  // float z = 3;
  void clear_z() ;
  float z() const;
  void set_z(float value);

  private:
  float _internal_z() const;
  void _internal_set_z(float value);

  public:
  // @@protoc_insertion_point(class_scope:Vector3D)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Vector3D& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    float x_;
    float y_;
    float z_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sensor_5fdata_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Vector3D_class_data_;
// -------------------------------------------------------------------

class AltimeterData final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:AltimeterData) */ {
 public:
  inline AltimeterData() : AltimeterData(nullptr) {}
  ~AltimeterData() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AltimeterData* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AltimeterData));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AltimeterData(::google::protobuf::internal::ConstantInitialized);

  inline AltimeterData(const AltimeterData& from) : AltimeterData(nullptr, from) {}
  inline AltimeterData(AltimeterData&& from) noexcept
      : AltimeterData(nullptr, ::std::move(from)) {}
  inline AltimeterData& operator=(const AltimeterData& from) {
    CopyFrom(from);
    return *this;
  }
  inline AltimeterData& operator=(AltimeterData&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AltimeterData& default_instance() {
    return *reinterpret_cast<const AltimeterData*>(
        &_AltimeterData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(AltimeterData& a, AltimeterData& b) { a.Swap(&b); }
  inline void Swap(AltimeterData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AltimeterData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AltimeterData* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<AltimeterData>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AltimeterData& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AltimeterData& from) { AltimeterData::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AltimeterData* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "AltimeterData"; }

 protected:
  explicit AltimeterData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  AltimeterData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const AltimeterData& from);
  AltimeterData(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, AltimeterData&& from) noexcept
      : AltimeterData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPressureFieldNumber = 1,
    kAltitudeFieldNumber = 2,
    kTemperatureFieldNumber = 3,
  };
  // float pressure = 1;
  void clear_pressure() ;
  float pressure() const;
  void set_pressure(float value);

  private:
  float _internal_pressure() const;
  void _internal_set_pressure(float value);

  public:
  // float altitude = 2;
  void clear_altitude() ;
  float altitude() const;
  void set_altitude(float value);

  private:
  float _internal_altitude() const;
  void _internal_set_altitude(float value);

  public:
  // float temperature = 3;
  void clear_temperature() ;
  float temperature() const;
  void set_temperature(float value);

  private:
  float _internal_temperature() const;
  void _internal_set_temperature(float value);

  public:
  // @@protoc_insertion_point(class_scope:AltimeterData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const AltimeterData& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    float pressure_;
    float altitude_;
    float temperature_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sensor_5fdata_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull AltimeterData_class_data_;
// -------------------------------------------------------------------

class ImuData final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ImuData) */ {
 public:
  inline ImuData() : ImuData(nullptr) {}
  ~ImuData() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ImuData* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ImuData));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ImuData(::google::protobuf::internal::ConstantInitialized);

  inline ImuData(const ImuData& from) : ImuData(nullptr, from) {}
  inline ImuData(ImuData&& from) noexcept
      : ImuData(nullptr, ::std::move(from)) {}
  inline ImuData& operator=(const ImuData& from) {
    CopyFrom(from);
    return *this;
  }
  inline ImuData& operator=(ImuData&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ImuData& default_instance() {
    return *reinterpret_cast<const ImuData*>(
        &_ImuData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(ImuData& a, ImuData& b) { a.Swap(&b); }
  inline void Swap(ImuData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ImuData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ImuData* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ImuData>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ImuData& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ImuData& from) { ImuData::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ImuData* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ImuData"; }

 protected:
  explicit ImuData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ImuData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ImuData& from);
  ImuData(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ImuData&& from) noexcept
      : ImuData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAccelerationFieldNumber = 1,
    kAngularVelocityFieldNumber = 2,
  };
  // .Vector3D acceleration = 1;
  bool has_acceleration() const;
  void clear_acceleration() ;
  const ::Vector3D& acceleration() const;
  [[nodiscard]] ::Vector3D* PROTOBUF_NULLABLE release_acceleration();
  ::Vector3D* PROTOBUF_NONNULL mutable_acceleration();
  void set_allocated_acceleration(::Vector3D* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_acceleration(::Vector3D* PROTOBUF_NULLABLE value);
  ::Vector3D* PROTOBUF_NULLABLE unsafe_arena_release_acceleration();

  private:
  const ::Vector3D& _internal_acceleration() const;
  ::Vector3D* PROTOBUF_NONNULL _internal_mutable_acceleration();

  public:
  // .Vector3D angular_velocity = 2;
  bool has_angular_velocity() const;
  void clear_angular_velocity() ;
  const ::Vector3D& angular_velocity() const;
  [[nodiscard]] ::Vector3D* PROTOBUF_NULLABLE release_angular_velocity();
  ::Vector3D* PROTOBUF_NONNULL mutable_angular_velocity();
  void set_allocated_angular_velocity(::Vector3D* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_angular_velocity(::Vector3D* PROTOBUF_NULLABLE value);
  ::Vector3D* PROTOBUF_NULLABLE unsafe_arena_release_angular_velocity();

  private:
  const ::Vector3D& _internal_angular_velocity() const;
  ::Vector3D* PROTOBUF_NONNULL _internal_mutable_angular_velocity();

  public:
  // @@protoc_insertion_point(class_scope:ImuData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   2, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ImuData& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::Vector3D* PROTOBUF_NULLABLE acceleration_;
    ::Vector3D* PROTOBUF_NULLABLE angular_velocity_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sensor_5fdata_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ImuData_class_data_;
// -------------------------------------------------------------------

class SensorPacket final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:SensorPacket) */ {
 public:
  inline SensorPacket() : SensorPacket(nullptr) {}
  ~SensorPacket() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SensorPacket* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SensorPacket));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SensorPacket(::google::protobuf::internal::ConstantInitialized);

  inline SensorPacket(const SensorPacket& from) : SensorPacket(nullptr, from) {}
  inline SensorPacket(SensorPacket&& from) noexcept
      : SensorPacket(nullptr, ::std::move(from)) {}
  inline SensorPacket& operator=(const SensorPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline SensorPacket& operator=(SensorPacket&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SensorPacket& default_instance() {
    return *reinterpret_cast<const SensorPacket*>(
        &_SensorPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(SensorPacket& a, SensorPacket& b) { a.Swap(&b); }
  inline void Swap(SensorPacket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SensorPacket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SensorPacket* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SensorPacket>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SensorPacket& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SensorPacket& from) { SensorPacket::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SensorPacket* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "SensorPacket"; }

 protected:
  explicit SensorPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SensorPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SensorPacket& from);
  SensorPacket(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SensorPacket&& from) noexcept
      : SensorPacket(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTimestampFieldNumber = 1,
    kImuDataFieldNumber = 2,
    kAltimeterDataFieldNumber = 3,
  };
  // .google.protobuf.Timestamp timestamp = 1;
  bool has_timestamp() const;
  void clear_timestamp() ;
  const ::google::protobuf::Timestamp& timestamp() const;
  [[nodiscard]] ::google::protobuf::Timestamp* PROTOBUF_NULLABLE release_timestamp();
  ::google::protobuf::Timestamp* PROTOBUF_NONNULL mutable_timestamp();
  void set_allocated_timestamp(::google::protobuf::Timestamp* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_timestamp(::google::protobuf::Timestamp* PROTOBUF_NULLABLE value);
  ::google::protobuf::Timestamp* PROTOBUF_NULLABLE unsafe_arena_release_timestamp();

  private:
  const ::google::protobuf::Timestamp& _internal_timestamp() const;
  ::google::protobuf::Timestamp* PROTOBUF_NONNULL _internal_mutable_timestamp();

  public:
  // .ImuData imu_data = 2;
  bool has_imu_data() const;
  void clear_imu_data() ;
  const ::ImuData& imu_data() const;
  [[nodiscard]] ::ImuData* PROTOBUF_NULLABLE release_imu_data();
  ::ImuData* PROTOBUF_NONNULL mutable_imu_data();
  void set_allocated_imu_data(::ImuData* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_imu_data(::ImuData* PROTOBUF_NULLABLE value);
  ::ImuData* PROTOBUF_NULLABLE unsafe_arena_release_imu_data();

  private:
  const ::ImuData& _internal_imu_data() const;
  ::ImuData* PROTOBUF_NONNULL _internal_mutable_imu_data();

  public:
  // .AltimeterData altimeter_data = 3;
  bool has_altimeter_data() const;
  void clear_altimeter_data() ;
  const ::AltimeterData& altimeter_data() const;
  [[nodiscard]] ::AltimeterData* PROTOBUF_NULLABLE release_altimeter_data();
  ::AltimeterData* PROTOBUF_NONNULL mutable_altimeter_data();
  void set_allocated_altimeter_data(::AltimeterData* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_altimeter_data(::AltimeterData* PROTOBUF_NULLABLE value);
  ::AltimeterData* PROTOBUF_NULLABLE unsafe_arena_release_altimeter_data();

  private:
  const ::AltimeterData& _internal_altimeter_data() const;
  ::AltimeterData* PROTOBUF_NONNULL _internal_mutable_altimeter_data();

  public:
  // @@protoc_insertion_point(class_scope:SensorPacket)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   3, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SensorPacket& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::Timestamp* PROTOBUF_NULLABLE timestamp_;
    ::ImuData* PROTOBUF_NULLABLE imu_data_;
    ::AltimeterData* PROTOBUF_NULLABLE altimeter_data_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sensor_5fdata_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull SensorPacket_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Vector3D

// float x = 1;
inline void Vector3D::clear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline float Vector3D::x() const {
  // @@protoc_insertion_point(field_get:Vector3D.x)
  return _internal_x();
}
inline void Vector3D::set_x(float value) {
  _internal_set_x(value);
  _impl_._has_bits_[0] |= 0x00000001U;
  // @@protoc_insertion_point(field_set:Vector3D.x)
}
inline float Vector3D::_internal_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_;
}
inline void Vector3D::_internal_set_x(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = value;
}

// float y = 2;
inline void Vector3D::clear_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline float Vector3D::y() const {
  // @@protoc_insertion_point(field_get:Vector3D.y)
  return _internal_y();
}
inline void Vector3D::set_y(float value) {
  _internal_set_y(value);
  _impl_._has_bits_[0] |= 0x00000002U;
  // @@protoc_insertion_point(field_set:Vector3D.y)
}
inline float Vector3D::_internal_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_;
}
inline void Vector3D::_internal_set_y(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = value;
}

// float z = 3;
inline void Vector3D::clear_z() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004U;
}
inline float Vector3D::z() const {
  // @@protoc_insertion_point(field_get:Vector3D.z)
  return _internal_z();
}
inline void Vector3D::set_z(float value) {
  _internal_set_z(value);
  _impl_._has_bits_[0] |= 0x00000004U;
  // @@protoc_insertion_point(field_set:Vector3D.z)
}
inline float Vector3D::_internal_z() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.z_;
}
inline void Vector3D::_internal_set_z(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z_ = value;
}

// -------------------------------------------------------------------

// ImuData

// .Vector3D acceleration = 1;
inline bool ImuData::has_acceleration() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001U) != 0;
  PROTOBUF_ASSUME(!value || _impl_.acceleration_ != nullptr);
  return value;
}
inline void ImuData::clear_acceleration() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.acceleration_ != nullptr) _impl_.acceleration_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::Vector3D& ImuData::_internal_acceleration() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Vector3D* p = _impl_.acceleration_;
  return p != nullptr ? *p : reinterpret_cast<const ::Vector3D&>(::_Vector3D_default_instance_);
}
inline const ::Vector3D& ImuData::acceleration() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ImuData.acceleration)
  return _internal_acceleration();
}
inline void ImuData::unsafe_arena_set_allocated_acceleration(
    ::Vector3D* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.acceleration_);
  }
  _impl_.acceleration_ = reinterpret_cast<::Vector3D*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ImuData.acceleration)
}
inline ::Vector3D* PROTOBUF_NULLABLE ImuData::release_acceleration() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001U;
  ::Vector3D* released = _impl_.acceleration_;
  _impl_.acceleration_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Vector3D* PROTOBUF_NULLABLE ImuData::unsafe_arena_release_acceleration() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ImuData.acceleration)

  _impl_._has_bits_[0] &= ~0x00000001U;
  ::Vector3D* temp = _impl_.acceleration_;
  _impl_.acceleration_ = nullptr;
  return temp;
}
inline ::Vector3D* PROTOBUF_NONNULL ImuData::_internal_mutable_acceleration() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.acceleration_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Vector3D>(GetArena());
    _impl_.acceleration_ = reinterpret_cast<::Vector3D*>(p);
  }
  return _impl_.acceleration_;
}
inline ::Vector3D* PROTOBUF_NONNULL ImuData::mutable_acceleration()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001U;
  ::Vector3D* _msg = _internal_mutable_acceleration();
  // @@protoc_insertion_point(field_mutable:ImuData.acceleration)
  return _msg;
}
inline void ImuData::set_allocated_acceleration(::Vector3D* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.acceleration_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }

  _impl_.acceleration_ = reinterpret_cast<::Vector3D*>(value);
  // @@protoc_insertion_point(field_set_allocated:ImuData.acceleration)
}

// .Vector3D angular_velocity = 2;
inline bool ImuData::has_angular_velocity() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002U) != 0;
  PROTOBUF_ASSUME(!value || _impl_.angular_velocity_ != nullptr);
  return value;
}
inline void ImuData::clear_angular_velocity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.angular_velocity_ != nullptr) _impl_.angular_velocity_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline const ::Vector3D& ImuData::_internal_angular_velocity() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Vector3D* p = _impl_.angular_velocity_;
  return p != nullptr ? *p : reinterpret_cast<const ::Vector3D&>(::_Vector3D_default_instance_);
}
inline const ::Vector3D& ImuData::angular_velocity() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ImuData.angular_velocity)
  return _internal_angular_velocity();
}
inline void ImuData::unsafe_arena_set_allocated_angular_velocity(
    ::Vector3D* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.angular_velocity_);
  }
  _impl_.angular_velocity_ = reinterpret_cast<::Vector3D*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002U;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ImuData.angular_velocity)
}
inline ::Vector3D* PROTOBUF_NULLABLE ImuData::release_angular_velocity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002U;
  ::Vector3D* released = _impl_.angular_velocity_;
  _impl_.angular_velocity_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Vector3D* PROTOBUF_NULLABLE ImuData::unsafe_arena_release_angular_velocity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ImuData.angular_velocity)

  _impl_._has_bits_[0] &= ~0x00000002U;
  ::Vector3D* temp = _impl_.angular_velocity_;
  _impl_.angular_velocity_ = nullptr;
  return temp;
}
inline ::Vector3D* PROTOBUF_NONNULL ImuData::_internal_mutable_angular_velocity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.angular_velocity_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Vector3D>(GetArena());
    _impl_.angular_velocity_ = reinterpret_cast<::Vector3D*>(p);
  }
  return _impl_.angular_velocity_;
}
inline ::Vector3D* PROTOBUF_NONNULL ImuData::mutable_angular_velocity()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002U;
  ::Vector3D* _msg = _internal_mutable_angular_velocity();
  // @@protoc_insertion_point(field_mutable:ImuData.angular_velocity)
  return _msg;
}
inline void ImuData::set_allocated_angular_velocity(::Vector3D* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.angular_velocity_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002U;
  }

  _impl_.angular_velocity_ = reinterpret_cast<::Vector3D*>(value);
  // @@protoc_insertion_point(field_set_allocated:ImuData.angular_velocity)
}

// -------------------------------------------------------------------

// AltimeterData

// float pressure = 1;
inline void AltimeterData::clear_pressure() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pressure_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline float AltimeterData::pressure() const {
  // @@protoc_insertion_point(field_get:AltimeterData.pressure)
  return _internal_pressure();
}
inline void AltimeterData::set_pressure(float value) {
  _internal_set_pressure(value);
  _impl_._has_bits_[0] |= 0x00000001U;
  // @@protoc_insertion_point(field_set:AltimeterData.pressure)
}
inline float AltimeterData::_internal_pressure() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pressure_;
}
inline void AltimeterData::_internal_set_pressure(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pressure_ = value;
}

// float altitude = 2;
inline void AltimeterData::clear_altitude() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.altitude_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline float AltimeterData::altitude() const {
  // @@protoc_insertion_point(field_get:AltimeterData.altitude)
  return _internal_altitude();
}
inline void AltimeterData::set_altitude(float value) {
  _internal_set_altitude(value);
  _impl_._has_bits_[0] |= 0x00000002U;
  // @@protoc_insertion_point(field_set:AltimeterData.altitude)
}
inline float AltimeterData::_internal_altitude() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.altitude_;
}
inline void AltimeterData::_internal_set_altitude(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.altitude_ = value;
}

// float temperature = 3;
inline void AltimeterData::clear_temperature() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.temperature_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004U;
}
inline float AltimeterData::temperature() const {
  // @@protoc_insertion_point(field_get:AltimeterData.temperature)
  return _internal_temperature();
}
inline void AltimeterData::set_temperature(float value) {
  _internal_set_temperature(value);
  _impl_._has_bits_[0] |= 0x00000004U;
  // @@protoc_insertion_point(field_set:AltimeterData.temperature)
}
inline float AltimeterData::_internal_temperature() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.temperature_;
}
inline void AltimeterData::_internal_set_temperature(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.temperature_ = value;
}

// -------------------------------------------------------------------

// SensorPacket

// .google.protobuf.Timestamp timestamp = 1;
inline bool SensorPacket::has_timestamp() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001U) != 0;
  PROTOBUF_ASSUME(!value || _impl_.timestamp_ != nullptr);
  return value;
}
inline const ::google::protobuf::Timestamp& SensorPacket::_internal_timestamp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::google::protobuf::Timestamp* p = _impl_.timestamp_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::protobuf::Timestamp&>(::google::protobuf::_Timestamp_default_instance_);
}
inline const ::google::protobuf::Timestamp& SensorPacket::timestamp() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:SensorPacket.timestamp)
  return _internal_timestamp();
}
inline void SensorPacket::unsafe_arena_set_allocated_timestamp(
    ::google::protobuf::Timestamp* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.timestamp_);
  }
  _impl_.timestamp_ = reinterpret_cast<::google::protobuf::Timestamp*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:SensorPacket.timestamp)
}
inline ::google::protobuf::Timestamp* PROTOBUF_NULLABLE SensorPacket::release_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001U;
  ::google::protobuf::Timestamp* released = _impl_.timestamp_;
  _impl_.timestamp_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::google::protobuf::Timestamp* PROTOBUF_NULLABLE SensorPacket::unsafe_arena_release_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:SensorPacket.timestamp)

  _impl_._has_bits_[0] &= ~0x00000001U;
  ::google::protobuf::Timestamp* temp = _impl_.timestamp_;
  _impl_.timestamp_ = nullptr;
  return temp;
}
inline ::google::protobuf::Timestamp* PROTOBUF_NONNULL SensorPacket::_internal_mutable_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.timestamp_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::google::protobuf::Timestamp>(GetArena());
    _impl_.timestamp_ = reinterpret_cast<::google::protobuf::Timestamp*>(p);
  }
  return _impl_.timestamp_;
}
inline ::google::protobuf::Timestamp* PROTOBUF_NONNULL SensorPacket::mutable_timestamp()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001U;
  ::google::protobuf::Timestamp* _msg = _internal_mutable_timestamp();
  // @@protoc_insertion_point(field_mutable:SensorPacket.timestamp)
  return _msg;
}
inline void SensorPacket::set_allocated_timestamp(::google::protobuf::Timestamp* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.timestamp_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }

  _impl_.timestamp_ = reinterpret_cast<::google::protobuf::Timestamp*>(value);
  // @@protoc_insertion_point(field_set_allocated:SensorPacket.timestamp)
}

// .ImuData imu_data = 2;
inline bool SensorPacket::has_imu_data() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002U) != 0;
  PROTOBUF_ASSUME(!value || _impl_.imu_data_ != nullptr);
  return value;
}
inline void SensorPacket::clear_imu_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.imu_data_ != nullptr) _impl_.imu_data_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline const ::ImuData& SensorPacket::_internal_imu_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::ImuData* p = _impl_.imu_data_;
  return p != nullptr ? *p : reinterpret_cast<const ::ImuData&>(::_ImuData_default_instance_);
}
inline const ::ImuData& SensorPacket::imu_data() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:SensorPacket.imu_data)
  return _internal_imu_data();
}
inline void SensorPacket::unsafe_arena_set_allocated_imu_data(
    ::ImuData* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.imu_data_);
  }
  _impl_.imu_data_ = reinterpret_cast<::ImuData*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002U;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:SensorPacket.imu_data)
}
inline ::ImuData* PROTOBUF_NULLABLE SensorPacket::release_imu_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002U;
  ::ImuData* released = _impl_.imu_data_;
  _impl_.imu_data_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::ImuData* PROTOBUF_NULLABLE SensorPacket::unsafe_arena_release_imu_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:SensorPacket.imu_data)

  _impl_._has_bits_[0] &= ~0x00000002U;
  ::ImuData* temp = _impl_.imu_data_;
  _impl_.imu_data_ = nullptr;
  return temp;
}
inline ::ImuData* PROTOBUF_NONNULL SensorPacket::_internal_mutable_imu_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.imu_data_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::ImuData>(GetArena());
    _impl_.imu_data_ = reinterpret_cast<::ImuData*>(p);
  }
  return _impl_.imu_data_;
}
inline ::ImuData* PROTOBUF_NONNULL SensorPacket::mutable_imu_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002U;
  ::ImuData* _msg = _internal_mutable_imu_data();
  // @@protoc_insertion_point(field_mutable:SensorPacket.imu_data)
  return _msg;
}
inline void SensorPacket::set_allocated_imu_data(::ImuData* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.imu_data_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002U;
  }

  _impl_.imu_data_ = reinterpret_cast<::ImuData*>(value);
  // @@protoc_insertion_point(field_set_allocated:SensorPacket.imu_data)
}

// .AltimeterData altimeter_data = 3;
inline bool SensorPacket::has_altimeter_data() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004U) != 0;
  PROTOBUF_ASSUME(!value || _impl_.altimeter_data_ != nullptr);
  return value;
}
inline void SensorPacket::clear_altimeter_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.altimeter_data_ != nullptr) _impl_.altimeter_data_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004U;
}
inline const ::AltimeterData& SensorPacket::_internal_altimeter_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::AltimeterData* p = _impl_.altimeter_data_;
  return p != nullptr ? *p : reinterpret_cast<const ::AltimeterData&>(::_AltimeterData_default_instance_);
}
inline const ::AltimeterData& SensorPacket::altimeter_data() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:SensorPacket.altimeter_data)
  return _internal_altimeter_data();
}
inline void SensorPacket::unsafe_arena_set_allocated_altimeter_data(
    ::AltimeterData* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.altimeter_data_);
  }
  _impl_.altimeter_data_ = reinterpret_cast<::AltimeterData*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004U;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:SensorPacket.altimeter_data)
}
inline ::AltimeterData* PROTOBUF_NULLABLE SensorPacket::release_altimeter_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000004U;
  ::AltimeterData* released = _impl_.altimeter_data_;
  _impl_.altimeter_data_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::AltimeterData* PROTOBUF_NULLABLE SensorPacket::unsafe_arena_release_altimeter_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:SensorPacket.altimeter_data)

  _impl_._has_bits_[0] &= ~0x00000004U;
  ::AltimeterData* temp = _impl_.altimeter_data_;
  _impl_.altimeter_data_ = nullptr;
  return temp;
}
inline ::AltimeterData* PROTOBUF_NONNULL SensorPacket::_internal_mutable_altimeter_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.altimeter_data_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::AltimeterData>(GetArena());
    _impl_.altimeter_data_ = reinterpret_cast<::AltimeterData*>(p);
  }
  return _impl_.altimeter_data_;
}
inline ::AltimeterData* PROTOBUF_NONNULL SensorPacket::mutable_altimeter_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000004U;
  ::AltimeterData* _msg = _internal_mutable_altimeter_data();
  // @@protoc_insertion_point(field_mutable:SensorPacket.altimeter_data)
  return _msg;
}
inline void SensorPacket::set_allocated_altimeter_data(::AltimeterData* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.altimeter_data_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004U;
  }

  _impl_.altimeter_data_ = reinterpret_cast<::AltimeterData*>(value);
  // @@protoc_insertion_point(field_set_allocated:SensorPacket.altimeter_data)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // sensor_5fdata_2eproto_2epb_2eh
