#pragma once

#include <cstdlib>
#include <assert.h>
#include <cstring>
#include <fcntl.h>
#include <unistd.h>
#include <sys/ioctl.h>
#include <Eigen/Dense>
#include <Eigen/Geometry>
#include <PIDcalculator.hpp>
#include <collection.hpp>
#include <drone.hpp>
#include <imu_generation.hpp>
#include <joint.hpp>
#include <json.hpp>
#include <physics_body.hpp>
#include <positionController.hpp>
#include <rigid_body.hpp>
#include <simulation.hpp>
#include <spi_interface.hpp>
#include <rc_parser.hpp>
#include <spi_new_test.hpp>
#include <velocityController.hpp>
#include <linux/spi/spidev.h>
