name: Basic Zephyr Build Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Zephyr Application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git cmake ninja-build gperf \
          ccache dfu-util device-tree-compiler wget \
          python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file \
          make gcc gcc-multilib g++-multilib libsdl2-dev libmagic1

    - name: Install West
      run: |
        pip3 install --user -U west
        echo 'export PATH=~/.local/bin:"$PATH"' >> $GITHUB_ENV

    - name: Initialize Zephyr workspace
      run: |
        west init -m https://github.com/zephyrproject-rtos/zephyr --mr main zephyrproject
        cd zephyrproject
        west update
        west zephyr-export

    - name: Install Zephyr dependencies
      run: |
        pip3 install --user -r zephyrproject/zephyr/scripts/requirements.txt

    - name: Set up Zephyr environment
      run: |
        cd zephyrproject
        echo 'export ZEPHYR_BASE=$PWD/zephyr' >> $GITHUB_ENV
        echo 'export PATH=$PWD/zephyr/scripts:$PATH' >> $GITHUB_ENV

    - name: Build test_node application
      run: |
        cd zephyrproject
        west build -p auto -b qemu_x86 $GITHUB_WORKSPACE/test_node/app

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: zephyr-build
        path: zephyrproject/build/
